# Reward Competition: High vs. Low Competition Level

In [2]:
import sys
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import wilcoxon
from scipy.signal import find_peaks
from rc_extension import Reward_Competition

PROJECT_ROOT = os.path.abspath(os.path.join(os.getcwd(), '..'))
sys.path.append(PROJECT_ROOT)

In [3]:
experiment_path = r"D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts"
manual_scoring_path = r"D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\manual_scoring_combined.xlsx"
hvl_path = r"D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\HvL_comp_scoring_updated.xlsx"

## HvL Preprocessing

In [4]:
rc_exp = Reward_Competition(experiment_folder_path=experiment_path, behavior_folder_path=None)
rc_exp.rtc_processing()
rc_exp.read_and_merge_manual_scoring(manual_scoring_path)
rc_exp.remove_specified_subjects()   # Remove specified subjects from the analysis
rc_exp.read_hvl_scoring(hvl_path)
rc_exp.remove_tangles(placeholders= True)   # Remove sound cues and winner array indexes where there are tangles
rc_exp.extract_da_columns()   # Grab only essential columns for analysis
rc_exp.find_first_port_entry_after_sound_cue()
rc_exp.compute_EI_DA(tone_window=(-5,10),
                  pe_window=(0,10),
                  baseline_window=(-20,-10))
rc_exp.compute_pretrial_EI_DA(pretrial_window=(-10,0),
                  baseline_window=(-14,-10))
rc_exp.compute_rtc_da_metrics(include_pretrial=True, bout_duration=4).head()

Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\n5-240912-080246\Notes.txt
read from t=0s to t=2051.77s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\n5-240913-094304\Notes.txt
read from t=0s to t=2044.77s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\n5-240915-060250\Notes.txt
read from t=0s to t=2044.96s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\n5-240915-095000\Notes.txt
read from t=0s to t=2070.66s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\n7-240912-095235\Notes.txt
read from t=0s to t=1955.86s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\n7-240913-080108\Notes.txt
read from t=0s to t=2044.86s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\n7-240914-082547\Notes.txt
read from t=0s to t=2075.17s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\n7-240915-073140\Notes.txt
read from t=0s to t=2046.16s
read from t=0s to t=2055.26s
read from t=0s to t=2055.26s
read from t=0s to t=2061.76s
read from t=0s to t=2061.76s
read from t=0s to t=2052.17s
read from t=0s to t=2052.17s
read from t=0s to t=2047.56s
read from t=0s to t=2047.56s
read from t=0s to t=2049.47s
read from t=0s to t=2049.47s
read from t=0s to t=2059.26s
read from t=0s to t=2059.26s
read from t=0s to t=2065.26s
read from t=0s to t=2065.26s
read from t=0s to t=2431.87s
read from t=0s to t=2431.87s
read from t=0s to t=2072.35s
read from t=0s to t=2072.35s
read from t=0s to t=2044.46s
read from t=0s to t=2044.46s
read from t=0s to t=2045.26s
read from t=0s to t=2045.26s
read from t=0s to t=2046.06s
read from t=0s to t=2046.06s
read from t=0s to t=2065.37s
read from t=0s to t=2065.37s
read from t=0s to t=2044.26s
read from t=0s to t=2044.26s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p1-240611-082555\Notes.txt
read from t=0s to t=2049.07s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p1-240612-104753\Notes.txt
read from t=0s to t=2046.43s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p1-240614-064528\Notes.txt
read from t=0s to t=2058.51s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p2-240611-065329\Notes.txt
read from t=0s to t=2041.61s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p2-240612-063828\Notes.txt
read from t=0s to t=2041.68s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p2-240613-104938\Notes.txt
read from t=0s to t=2042.47s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p3-240611-110619\Notes.txt
read from t=0s to t=2041.61s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p3-240613-080730\Notes.txt
read from t=0s to t=2041.81s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p3-240614-081850\Notes.txt
read from t=0s to t=2116.13s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p5-240912-071257\Notes.txt
read from t=0s to t=2045.16s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p5-240913-085922\Notes.txt
read from t=0s to t=2044.47s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p5-240915-064653\Notes.txt
read from t=0s to t=2050.16s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p6-240912-052842\Notes.txt
read from t=0s to t=2045.86s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p6-240913-054041\Notes.txt
read from t=0s to t=2047.46s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p6-240914-091051\Notes.txt
read from t=0s to t=2044.66s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p7-240912-090250\Notes.txt
read from t=0s to t=2041.86s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p7-240914-074210\Notes.txt
read from t=0s to t=2044.26s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p8-240913-070924\Notes.txt
read from t=0s to t=2059.66s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p8-240914-061235\Notes.txt
read from t=0s to t=2046.86s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p8-240915-051905\Notes.txt
read from t=0s to t=2044.66s
Found Synapse note file: D:\PadillaCoreanoLab\Reward_Competition\combined_cohorts\p8-240915-081607\Notes.txt
read from t=0s to t=2084.46s
read from t=0s to t=2057.57s
read from t=0s to t=2057.57s
read from t=0s to t=2231.17s
read from t=0s to t=2231.17s
read from t=0s to t=2052.17s
read from t=0s to t=2052.17s
read from t=0s to t=2184.07s
read from t=0s to t=2184.07s
read from t=0s to t=2078.66s
read from t=0s to t=2078.66s
read from t=0s to t=2065.37s
read from t=0s to t=2065.37s
read from t=0s to t=2047.26s
read from t=0s to t=2047.26s
Processing trial n5-240912-080246...
Processing trial n5-240913-094304...
Processing trial n5-240915-060250...
Processing trial n5-240915-095000...
Processing trial n7-240912-095235...
Processing trial n7-240913-080108...
Processing trial n7-240914-082547...
Processing trial n7-240915-073140...
Processing trial nn1-250203-085508...
Processing trial nn3-250203-085508...
Processing trial nn1-250205-090150...
Processing trial pp1-250205-090150...
Processing trial nn2-250204-085225...
Processing trial nn1-250204-085225...
Processing trial nn2-250206-053033...
Processing trial pp2-250206-053033...
Processing trial nn3-250204-122327...
Processing trial pp3-250204-122327...
Processing trial nn4-250206-081929...
Processing trial nn3-250206-081929...
Processing trial nn4-250203-121223...
Processing trial pp4-250203-121223...
Processing trial nn5-250205-104235...
Processing trial nn8-250205-104235...
Processing trial nn5-250203-080636...
Processing trial pp5-250203-080636...
Processing trial nn6-250203-112333...
Processing trial nn7-250203-112333...
Processing trial nn6-250206-073116...
Processing trial nn7-250206-073116...
Processing trial nn7-250205-131504...
Processing trial pp7-250205-131504...
Processing trial nn8-250204-113128...
Processing trial nn5-250204-113128...
Processing trial nn8-250206-102501...
Processing trial pp8-250206-102501...
Processing trial p1-240611-082555...
Processing trial p1-240612-104753...
Processing trial p1-240614-064528...
Processing trial p2-240611-065329...
Processing trial p2-240612-063828...
Processing trial p2-240613-104938...
Processing trial p3-240611-110619...
Processing trial p3-240613-080730...
Processing trial p3-240614-081850...
Processing trial p5-240912-071257...
Processing trial p5-240913-085922...
Processing trial p5-240915-064653...
Processing trial p6-240912-052842...
Processing trial p6-240913-054041...
Processing trial p6-240914-091051...
Processing trial p7-240912-090250...
Processing trial p7-240914-074210...
Processing trial p8-240913-070924...
Processing trial p8-240914-061235...
Processing trial p8-240915-051905...
Processing trial p8-240915-081607...
Processing trial pp2-250204-095252...
Processing trial pp1-250204-095252...
Processing trial pp2-250205-122507...
Processing trial pp4-250205-122507...
Processing trial pp4-250206-093423...
Processing trial pp3-250206-093423...
Processing trial pp5-250205-095320...
Processing trial pp8-250205-095320...
Processing trial pp6-250204-075106...
Processing trial nn6-250204-075106...
Processing trial pp6-250206-062728...
Processing trial pp7-250206-062728...
Processing trial pp8-250204-104135...
Processing trial pp5-250204-104135...
Total rows: 96
Rows with missing trials: 25

c:\Users\zhaoz\Desktop\Research\Dopamine Project\Fiber_Photometry_revisions\Reward_Training-Competition\Reward_Competition\rc_extension.py:474: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  hv[pre_cols]  = hv[pre_cols].replace('T', np.nan).apply(pd.to_numeric, errors='coerce')
c:\Users\zhaoz\Desktop\Research\Dopamine Project\Fiber_Photometry_revisions\Reward_Training-Competition\Reward_Competition\rc_extension.py:475: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  hv[comp_cols] = hv[comp_cols].replace('T', np.nan).apply(pd.to_numeric, errors='coerce')

,subject_name,file name,trial,filtered_sound_cues,filtered_port_entries,filtered_port_entry_offset,filtered_winner_array,HVL_PreComp,HVL_Comp,first_PE_after_sound_cue,...,Tone Time of Max Peak,Tone Mean Z-score,PE AUC,PE Max Peak,PE Time of Max Peak,PE Mean Z-score,Pretrial AUC,Pretrial Max Peak,Pretrial Time of Max Peak,Pretrial Mean Z-score
0,nn5,nn5-250203-080636,<trial_class.Trial object at 0x0000029DD749BF80>,"[241.12775168, 321.12836608, 411.12895488, 491...","[184.1774592, 185.80733952, 193.31743744, 285....","[184.47745024, 187.45769984, 193.45752064, 285...","[tie, nn8, nn8, nn8, nn8, nn8, nn8, nn8, nn8, ...","[nan, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[285.35799808, 325.12836608, 415.12895488, 495...",...,"[0.7599999998637941, 0.7299999998645035, 0.849...","[0.5802336747137268, 1.0628530397409286, 0.351...","[0.6171770231792162, 0.8103694032097739, 1.302...","[1.7444741505890045, 1.0771713947169135, 1.236...","[0.0, 3.329999999921256, 1.729999999959091, 3....","[0.15554037603863283, 0.20191823874917406, 0.3...","[-2.849382550168764, -1.3336872573869143, 0.66...","[0.5931472481063685, 1.0071056302787829, 1.468...","[-8.490000000035707, -3.4200000001555964, -0.8...","[-0.2852658182810076, -0.1337081639029117, 0.0..."
1,pp5,pp5-250203-080636,<trial_class.Trial object at 0x0000029DD710A4E0>,"[241.12775168, 321.12836608, 411.12895488, 491...","[181.1275776, 184.02738176, 185.90744576, 187....","[181.68741888, 185.52766464, 186.98747904, 187...","[pp5, pp5, pp5, pp5, pp8, pp5, pp8, tangle, ta...","[0.0, 0.0, nan, 1.0, 1.0, 0.0, nan, nan, nan, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, nan, nan, nan, ...","[245.12775168, 325.12836608, 415.12895488, 495...",...,"[1.5599999998448766, 0.30999999987443516, 3.99...","[0.2669676790867533, 0.1852523567749728, -0.63...","[5.950139337912823, 0.014127306905708237, 2.29...","[2.8878636660121964, 1.4146806890091848, 1.390...","[1.6799999999602733, 2.769999999934498, 3.5499...","[1.486451562915203, 0.0022014073336268122, 0.5...","[1.8332802116328355, 1.7517189334442307, 2.378...","[1.4933537085859405, 1.404225722707683, 2.0700...","[-2.9000000001678927, -9.35000000001537, -6.44...","[0.1830518255475024, 0.1757293702764755, 0.237..."
2,nn1,nn1-250203-085508,<trial_class.Trial object at 0x0000029DD75DA9F0>,"[250.00820736, 330.00865792, 420.00941056, 500...","[194.11779584, 203.48796928, 215.75778304, 217...","[196.25771008, 206.667776, 217.06801152, 217.8...","[nn2, nn1, nn1, nn1, nn1, nn1, nn2, nn2, nn1, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, nan, nan, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, nan, nan, 0.0, ...","[254.00820736, 334.00865792, 424.00941056, 504...",...,"[1.7699999998399107, 0.7599999998637941, 0.919...","[-0.5260376430763154, 0.7905916884713389, 0.63...","[-0.38772886319409317, 3.201734063472012, 1.82...","[0.4053416088639346, 4.294016009135805, 2.3342...","[2.0799999999508145, 0.8999999999787178, 0.829...","[-0.09679108789204786, 0.7968868844887507, 0.4...","[-6.219682915576498, -4.024362126982294, -5.54...","[1.4058687016702707, 0.7591264878106921, 2.433...","[-9.640000000008513, -9.910000000002128, -6.30...","[-0.6218682903413478, -0.4018647191271188, -0...."
3,nn3,nn3-250203-085508,<trial_class.Trial object at 0x0000029DD741ABD0>,"[250.00820736, 330.00865792, 420.00941056, 500...","[219.1179776, 230.92805632, 231.34830592, 244....","[225.37814016, 231.26818816, 232.78813184, 246...","[nn3, nn4, nn3, nn4, nn4, nn4, nn4, nn4, nn4, ...","[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, ...","[254.00820736, 334.00865792, 424.00941056, 504...",...,"[0.8099999998626117, 0.71999999986474, 0.69999...","[1.9646313990298285, 0.9896661193221952, 2.228...","[9.073446319493542, 1.5730904070593548, 10.878...","[5.7039152776901885, 1.2824150996300059, 7.441...","[1.1599999999725696, 2.599999999938518, 1.0599...","[2.265042353999151, 0.39369404810126674, 2.714...","[-6.017835433214398, 0.10725436608586314, 3.52...","[0.23778871533175086, 2.0529182903372805, 2.70...","[-6.0000000000945874, -7.020000000070468, -1.3...","[-0.6019130794952536, 0.00968747857285178, 0.3..."
4,nn6,nn6-250203-112333,<trial_class.Trial object at 0x0000029DD9140C20>,"[240.79777792, 320.79822848, 410.79881728, nan...","[180.79727616, 184.92735488, 189.60744448, nan...","[184.34736128, 187.74720512, 189.75768576, nan...","[nn5, nn6, tie, tangle, nn6, nn6, tangle, nn6,...","[0.0, 0.0, nan, 0.0, 0.0, nan, 0.0, 1.0, 0.0, ...","[0.0, 1.0, nan, 0.0, 0.0, nan, 0.0, 0.0, 0.0, ...","[302.28840448, 327.32823552, 427.75887872, nan...",...,"[0.5799999998680505, 0.5999999998675776, 0.549...","[-0.8285754307724682, 2.749970385484245, -0.51...","[2.2735477429906177, 14.242439309089516, 2.603...","[1.828324934129389, 8.793936402004235, 2.98648...","[2.3799999999437205, 0.0, 0.1599999999962165, ...","[0.5678597888165446, 3.5648208725810377, 0.651...","[-5.394917663002101, 0.9552884502622727, -5.62...","[1.4413326314019117, 2.760199598053706, 0.2550...","[-10.0, -6.440000000084183, -8.78000000002885,...","[-0.5389265416652091, 0.0956528747881959, -0.5..."

In [ ]:
rc_exp.da_df.loc[rc_exp.da_df['file name'] == 'nn1-250203-085508', 'filtered_sound_cues'].iloc[0]

NameError: name 'rc_exp' is not defined

In [5]:
# mPFC subjects only dataframe
mPFC_rc_exp = rc_exp.da_df[rc_exp.da_df['subject_name'].str.startswith('p')]
print(len(mPFC_rc_exp))
mPFC_rc_exp.head()

41

,subject_name,file name,trial,filtered_sound_cues,filtered_port_entries,filtered_port_entry_offset,filtered_winner_array,HVL_PreComp,HVL_Comp,first_PE_after_sound_cue,...,Tone Time of Max Peak,Tone Mean Z-score,PE AUC,PE Max Peak,PE Time of Max Peak,PE Mean Z-score,Pretrial AUC,Pretrial Max Peak,Pretrial Time of Max Peak,Pretrial Mean Z-score
1,pp5,pp5-250203-080636,<trial_class.Trial object at 0x000001FC02A1B290>,"[241.12775168, 321.12836608, 411.12895488, 491...","[181.1275776, 184.02738176, 185.90744576, 187....","[181.68741888, 185.52766464, 186.98747904, 187...","[pp5, pp5, pp5, pp5, pp8, pp5, pp8, tangle, ta...","[0.0, 0.0, nan, 1.0, 1.0, 0.0, nan, nan, nan, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, nan, nan, nan, ...","[245.12775168, 325.12836608, 415.12895488, 495...",...,"[1.5599999998448766, 0.30999999987443516, 3.99...","[0.2669676790867533, 0.1852523567749728, -0.63...","[5.950139337912823, 0.014127306905708237, 2.29...","[2.8878636660121964, 1.4146806890091848, 1.390...","[1.6799999999602733, 2.769999999934498, 3.5499...","[1.486451562915203, 0.0022014073336268122, 0.5...","[1.8332802116328355, 1.7517189334442307, 2.378...","[1.4933537085859405, 1.404225722707683, 2.0700...","[-2.9000000001678927, -9.35000000001537, -6.44...","[0.1830518255475024, 0.1757293702764755, 0.237..."
7,pp4,pp4-250203-121223,<trial_class.Trial object at 0x000001FC029D50A0>,"[243.716096, nan, nan, nan, nan, nan, nan, nan...","[187.95544576, nan, nan, nan, nan, nan, nan, n...","[193.52600576, nan, nan, nan, nan, nan, nan, n...","[pp4, tangle, tangle, tangle, tangle, tangle, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[264.39614464, nan, nan, nan, nan, nan, nan, n...",...,"[3.8499999997907253, nan, nan, nan, nan, nan, ...","[-0.9358412702915131, nan, nan, nan, nan, nan,...","[6.260050712827287, nan, nan, nan, nan, nan, n...","[2.809647338769118, nan, nan, nan, nan, nan, n...","[2.5499999999397005, nan, nan, nan, nan, nan, ...","[1.5654388136339699, nan, nan, nan, nan, nan, ...","[-12.682009379794703, nan, nan, nan, nan, nan,...","[1.7235509172971957, nan, nan, nan, nan, nan, ...","[-1.9000000001915396, nan, nan, nan, nan, nan,...","[-1.2679989901645685, nan, nan, nan, nan, nan,..."
9,pp1,pp1-250205-090150,<trial_class.Trial object at 0x000001FC00366F00>,"[241.1626496, nan, 411.16401664, 491.16413952,...","[181.16231168, nan, 190.11239936, 190.52249088...","[181.99232512, nan, 190.48267776, 190.62243328...","[pp4, tangle, pp1, pp4, pp4, pp4, pp1, tangle,...","[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, nan, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, nan, 0.0, 0.0, 0.0, ...","[246.34261504, nan, 415.16401664, 495.16413952...",...,"[1.6899999998418025, nan, 2.4099999998247768, ...","[-0.6266020500182463, nan, 1.1020370860277466,...","[1.2853140698801533, nan, 0.9371456843900628, ...","[1.701397888258207, nan, 1.9939580055971922, 2...","[3.7199999999120337, nan, 2.5899999999387546, ...","[0.3200861046144806, nan, 0.23370519888610852,...","[0.3363055009509661, nan, 10.433666787505604, ...","[1.9469861218608855, nan, 2.7347315168266757, ...","[-6.97000000007165, nan, -3.4600000001546505, ...","[0.03307545987105456, nan, 1.0433096851491601,..."
10,pp5,pp5-250205-095320,<trial_class.Trial object at 0x000001FC02A3C380>,"[240.6948864, 320.6955008, 410.69576192, 490.6...","[180.69438464, 193.3344768, 211.28462336, 218....","[185.18441984, 209.74485504, 214.79473152, 221...","[pp5, pp5, pp5, pp5, pp5, tie, pp5, pp5, pp5, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, nan, 0.0, 0.0, 0.0, ...","[244.6948864, 324.6955008, 414.69576192, 494.6...",...,"[2.8399999998146086, 0.7799999998633211, 1.959...","[0.5815986082760558, 0.324992539492864, 0.6317...","[3.1990444969931384, 1.8901631727444839, -0.52...","[1.4959049892589042, 0.8855829378734035, 0.695...","[1.239999999970678, 2.8099999999335523, 2.0399...","[0.799955300158309, 0.4720584852354011, -0.131...","[-2.4711109406688223, 4.2718221609921425, 6.13...","[0.9189001911124162, 0.7326617320239831, 0.904...","[-1.7500000001950866, -3.0600000001641092, -5....","[-0.2465383444794642, 0.42671692393993405, 0.6..."
11,pp8,pp8-250205-095320,<trial_class.Trial object at 0x000001FC024E3D70>,"[240.6948864, 320.6955008, 410.69576192, 490.6...","[180.69438464, 182.82446848, 184.1545216, 185....","[181.4642688, 183.91482368, 184.84477952, 187....","[pp8, pp7, pp7, pp7, pp7, pp7, pp7, pp8, pp7, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[260.90487808, 324.6955008, 414.69576192, 494....",...,"[1.2899999998512612, 3.7399999997933264, 3.049...","[-0.5947490837140227, -0.0034025181491655144, ...","[6.518672199894331, -1.6371525607254653, -0.87...","[4.291460603549999, 1.1659326400258503, 1.4743...","[3.7199999999120337, 1.3699999999676038, 2.419...","[1.6291448076303476, -0.40909632391335665, -0....","[-5.8207551478891, 4.260894441554983, -5.05444...","[1.3813532488968185, 2.4666985840807394, 2.199...","[-1.9000000001915396, -8.61000000003287, -0.80...","[-0.5818156189173673, 0.42548456215789227, -0...."

## Peak Detection Preprocessing

In [6]:
rc_exp.compute_spontaneous_events(threshold_factor=2.5, min_distance_s=0.5, min_width_s=0.3)

# Only keep mPFC subjects
rc_exp.spont_peaks = rc_exp.spont_peaks[rc_exp.spont_peaks['subject_name'].str.startswith('p')]
rc_exp.spont_peaks

      subject_name          file name  event_time  amplitude   width_s
300            pp5  pp5-250203-080636       34.96   1.670585  0.806484
301            pp5  pp5-250203-080636       76.14   2.685008  1.439022
302            pp5  pp5-250203-080636       78.27   2.632399  0.594543
303            pp5  pp5-250203-080636       84.92   1.552154  1.063272
304            pp5  pp5-250203-080636       93.33   2.487179  0.358935
...            ...                ...         ...        ...       ...
17949           p8   p8-240913-070924     2006.05   2.247527  0.660728
17950           p8   p8-240913-070924     2007.81   2.078742  0.479498
17951           p8   p8-240913-070924     2013.72   2.308905  5.113635
17952           p8   p8-240913-070924     2030.15   1.877577  0.496426
17953           p8   p8-240913-070924     2048.42   1.659949  1.323807

[8265 rows x 5 columns]

In [7]:
def detect_spontaneous_events(
	timestamps: np.ndarray,
	signal: np.ndarray,
	threshold_factor: float = 2.5,
	min_distance_s: float = 0.5,
	min_width_s:    float = 0.3
):
	"""
	Detect peaks using a MAD‐threshold, plus a minimum inter‐peak interval
	and a minimum peak width.
	Returns:
	peak_times (np.ndarray),
	peak_amps (np.ndarray),
	peak_widths (np.ndarray, in seconds)
	"""
	# 1) compute baseline + MAD
	med = np.median(signal)
	mad = np.median(np.abs(signal - med))
	thresh = med + threshold_factor * mad

	# 2) convert time criteria into sample counts (assumes uniform dt)
	dt = np.median(np.diff(timestamps))
	min_dist_samples  = int(np.round(min_distance_s / dt))
	min_width_samples = int(np.round(min_width_s    / dt))

	# 3) detect peaks
	peaks, props = find_peaks(
		signal,
		height=thresh,
		distance=min_dist_samples,
		width=min_width_samples
	)

	# 4) collect outputs
	peak_times  = timestamps[peaks]
	peak_amps   = signal[peaks]
	peak_widths = props["widths"] * dt

	return peak_times, peak_amps, peak_widths

In [8]:
def plot_trace_segment_with_peaks(
    da_df,
    time_window: tuple = (0, 60),
    threshold_factor: float = 3.0,
    min_distance_s: float = 1.0,
    min_width_s:    float = 0.5,
    region: str = None,          # 'NAc', 'mPFC' or None for all
    figsize_per_trace: tuple = (12, 2),
    mark_color: str = 'red',
    tone_line_color: str = 'gray',
    tone_line_style: str = '--'
):
    """
    Plot a time‐window segment of each session's z‐score trace, mark spontaneous peaks,
    and draw dashed vertical lines at each tone onset within that window.
    """
    t0, t1 = time_window

    # 1) optional region filter
    if region is not None:
        prefix = 'n' if region=='NAc' else 'p'
        df_plot = da_df[da_df['subject_name'].str.startswith(prefix)]
    else:
        df_plot = da_df

    if df_plot.empty:
        print("No sessions to plot.")
        return

    # 2) make one row per session
    n = len(df_plot)
    fig, axes = plt.subplots(n, 1,
                             figsize=(figsize_per_trace[0],
                                      figsize_per_trace[1]*n),
                             sharex=False)
    if n == 1:
        axes = [axes]

    for ax, (_, row) in zip(axes, df_plot.iterrows()):
        # --- slice the main trace ---
        ts_full = np.asarray(row['trial'].timestamps, dtype=float)
        zs_full = np.asarray(row['trial'].zscore,     dtype=float)
        mask    = (ts_full >= t0) & (ts_full <= t1)
        ts, zs  = ts_full[mask], zs_full[mask]

        # --- detect peaks in that slice ---
        peak_times, peak_amps, _ = detect_spontaneous_events(
            ts, zs,
            threshold_factor=threshold_factor,
            min_distance_s=min_distance_s,
            min_width_s=min_width_s
        )

        # --- plot the trace & peaks ---
        ax.plot(ts, zs, color='black', lw=1)
        ax.scatter(peak_times, peak_amps,
                   color=mark_color, s=40,
                   label='spontaneous peaks', zorder=5)

        # --- draw tone‐onset lines ---
        # pick your cue column here:
        cues = row.get('filtered_sound_cues', []) or []
        for cue in cues:
            if t0 <= cue <= t1:
                ax.axvline(cue, color=tone_line_color,
                           linestyle=tone_line_style, lw=1)

        ax.set_title(f"{row['file name']} ({row['subject_name']})", fontsize=10)
        ax.set_xlim(t0, t1)
        ax.set_ylabel("z ΔF/F", fontsize=9)
        ax.legend(loc='upper right', fontsize=8)

    axes[-1].set_xlabel("Time (s)", fontsize=10)
    plt.tight_layout()
    plt.show()

In [1]:
plot_trace_segment_with_peaks(
    rc_exp.da_df,
    time_window=(1200,1400),
    threshold_factor=2.5,
    min_distance_s=0.5,
    min_width_s=0.3,
    region='mPFC'
)

NameError: name 'plot_trace_segment_with_peaks' is not defined

In [10]:
cues = rc_exp.da_df.loc[
    rc_exp.da_df['file name'] == 'p3-240613-080730',
    'filtered_sound_cues'
].iloc[0]

print(cues)

cues = mPFC_rc_exp.loc[
    mPFC_rc_exp['file name'] == 'p6-240913-054041',
    'filtered_sound_cues'
].iloc[0]

print(cues)

# rc_exp.trials_df.loc[rc_exp.trials_df['file name'] == 'p3-240613-080730', 'sound cues'].iloc[0]

[240.99487744, 320.99549184, nan, 490.9965312, 496.406528, 565.99707648, 570.36488704, 574.93028864, nan, nan, nan, 850.99921408, nan, 1021.00025344, 1121.00098048, 1211.00140544, 1331.00240896, 1421.00299776, 1423.35279104, 1506.00351744, 1596.0039424, 1691.00460032, 1811.00544, 1891.00621824, 2040.98715648]
[239.96678144, 319.967232, 409.9678208, 489.96810752, 564.96881664, 664.96937984, 759.96987392, 849.97046272, 929.97091328, 1019.97133824, 1119.97206528, 1209.97249024, 1329.97316608, 1419.97391872, 1504.97427456, 1594.97469952, 1689.97535744, 1809.97603328, 1889.97648384, 2039.95725824]

## HvL Peak Counts

### 1. Relative to a Cue?

In [11]:
def compute_average_peak_hvl_1(
    da_df,
    spont_peaks,
	relative_to='filtered_sound_cues', 
	time_window = (-4, 10)
):
    total_peaks_timestamps = []
    total_peaks_low = 0
    total_peaks_high = 0
    total_low_comp = 0
    total_high_comp = 0
    total_tie = 0

    # For correct stats: store per-cue peak counts (then aggregate per session)
    cue_rows = []  # each entry: {'file', 'condition'(0/1), 'n_peaks'}

    # Loop through each recording/session
    for _, row in da_df.iterrows():
        peak_timestamps = []
        file_name = row['file name']
        trial_peaks = spont_peaks[spont_peaks['file name'] == file_name]

        hvl_labels = row.get('HVL_Comp') or []
        relative_timestamps = row.get(relative_to) or []

        # Loop safely over aligned indices
        n = min(len(hvl_labels), len(relative_timestamps))
        for i in range(n):
            # Skip NaN/None cue times
            if relative_timestamps[i] is None:
                continue
            
            # Only analyze low/high (0/1); count others as ties
            lab_int = hvl_labels[i]
            if lab_int == 0:
                total_low_comp += 1
            elif lab_int == 1:
                total_high_comp += 1
            else:
                total_tie += 1
                continue

            start = relative_timestamps[i] + time_window[0]
            end = relative_timestamps[i] + time_window[1]

            # Filter to get the peaks in window
            peaks_in_windows = trial_peaks[
                (trial_peaks['event_time'] >= start) &
                (trial_peaks['event_time'] <= end)
            ]
            n_peaks = int(len(peaks_in_windows))

            # Update totals
            if lab_int == 0:
                total_peaks_low += n_peaks
            elif lab_int == 1:
                total_peaks_high += n_peaks

            # Store cue-level count for session-level paired stats
            cue_rows.append({
                'file': file_name,
                'condition': lab_int,   # 0 low, 1 high
                'n_peaks': n_peaks
            })

            # Save peak timestamps for this session (optional)
            if n_peaks > 0:
                peak_timestamps.extend(peaks_in_windows['event_time'].tolist())

        total_peaks_timestamps.append(peak_timestamps)

    # Add column back into da_df
    da_df = da_df.copy()
    da_df['Timestamps of Peak in Comp'] = total_peaks_timestamps

    # Print totals
    print("Low competition:")
    print("  Total peaks:", total_peaks_low)
    print("  Total cues:", total_low_comp)
    print("  Average #:", (total_peaks_low / total_low_comp) if total_low_comp else np.nan)

    print("\nHigh competition:")
    print("  Total peaks:", total_peaks_high)
    print("  Total cues:", total_high_comp)
    print("  Average #:", (total_peaks_high / total_high_comp) if total_high_comp else np.nan)

    print("\nTotal ties:", total_tie)

    # -------------------------------
    # Correct paired session-level stats
    # -------------------------------
    cue_df = pd.DataFrame(cue_rows)
    if cue_df.empty:
        print("\n[Stats] No valid low/high cue windows found. Cannot run stats.")
        return da_df

    # Compute per-session mean peaks per cue for each condition
    session_means = (
        cue_df
        .groupby(['file', 'condition'])['n_peaks']
        .mean()
        .unstack('condition')   # columns: 0 (low), 1 (high) if present
    )

    # Keep only sessions that have BOTH conditions (paired)
    paired = session_means.dropna(subset=[0, 1], how='any')
    print(paired)

    if len(paired) < 2:
        print("\n[Stats] Not enough paired sessions (need >= 2 with both low and high) to run Wilcoxon.")
        return da_df

    low_means = paired[0].to_numpy()
    high_means = paired[1].to_numpy()
    diffs = high_means - low_means

    print("\n[Stats] Session-level mean peaks per cue")
    print("  n paired sessions:", len(paired))
    print("  Mean low:", float(np.mean(low_means)))
    print("  Mean high:", float(np.mean(high_means)))
    print("  Mean diff (high - low):", float(np.mean(diffs)))
    print("  Median diff (high - low):", float(np.median(diffs)))

    # Paired Wilcoxon signed-rank test
    w_stat, p_val = wilcoxon(high_means, low_means, zero_method='wilcox', alternative='two-sided')
    print("\nWilcoxon signed-rank test (paired)")
    print("  W statistic:", float(w_stat))
    print("  p-value:", float(p_val))

    # return da_df

In [12]:
compute_average_peak_hvl_1(mPFC_rc_exp, rc_exp.spont_peaks, relative_to = 'filtered_sound_cues', time_window = (0, 30))
mPFC_rc_exp.head()

Low competition:
  Total peaks: 1598
  Total cues: 549
  Average #: 2.9107468123861566

High competition:
  Total peaks: 143
  Total cues: 54
  Average #: 2.6481481481481484

Total ties: 176
condition               0.0        1.0
file
p1-240611-082555   1.307692   2.000000
p2-240613-104938   4.666667   5.000000
p3-240611-110619   2.400000   5.500000
p5-240912-071257   2.000000   0.000000
p5-240913-085922   2.294118   1.500000
p5-240915-064653   5.400000   0.600000
p7-240912-090250   1.888889   3.000000
p7-240914-074210   0.800000   1.000000
p8-240913-070924   2.352941   1.000000
p8-240915-051905   5.222222   1.857143
p8-240915-081607   2.300000   3.333333
pp2-250205-122507  2.846154   1.333333
pp3-250204-122327  3.277778  12.000000
pp3-250206-093423  3.230769   4.000000
pp5-250203-080636  3.200000   0.000000
pp5-250204-104135  1.818182   4.666667
pp5-250205-095320  2.400000   2.000000
pp7-250206-062728  2.692308   1.500000

[Stats] Session-level mean peaks per cue
  n paired sessions: 18
  Mean low: 2.7832066263438815
  Mean high: 2.7939153439153444
  Mean diff (high - low): 0.010708717571462634
  Median diff (high - low): -0.09999999999999998

Wilcoxon signed-rank test (paired)
  W statistic: 72.0
  p-value: 0.5798416137695312

,subject_name,file name,trial,filtered_sound_cues,filtered_port_entries,filtered_port_entry_offset,filtered_winner_array,HVL_PreComp,HVL_Comp,first_PE_after_sound_cue,...,Tone Time of Max Peak,Tone Mean Z-score,PE AUC,PE Max Peak,PE Time of Max Peak,PE Mean Z-score,Pretrial AUC,Pretrial Max Peak,Pretrial Time of Max Peak,Pretrial Mean Z-score
1,pp5,pp5-250203-080636,<trial_class.Trial object at 0x000001FC02A1B290>,"[241.12775168, 321.12836608, 411.12895488, 491...","[181.1275776, 184.02738176, 185.90744576, 187....","[181.68741888, 185.52766464, 186.98747904, 187...","[pp5, pp5, pp5, pp5, pp8, pp5, pp8, tangle, ta...","[0.0, 0.0, nan, 1.0, 1.0, 0.0, nan, nan, nan, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, nan, nan, nan, ...","[245.12775168, 325.12836608, 415.12895488, 495...",...,"[1.5599999998448766, 0.30999999987443516, 3.99...","[0.2669676790867533, 0.1852523567749728, -0.63...","[5.950139337912823, 0.014127306905708237, 2.29...","[2.8878636660121964, 1.4146806890091848, 1.390...","[1.6799999999602733, 2.769999999934498, 3.5499...","[1.486451562915203, 0.0022014073336268122, 0.5...","[1.8332802116328355, 1.7517189334442307, 2.378...","[1.4933537085859405, 1.404225722707683, 2.0700...","[-2.9000000001678927, -9.35000000001537, -6.44...","[0.1830518255475024, 0.1757293702764755, 0.237..."
7,pp4,pp4-250203-121223,<trial_class.Trial object at 0x000001FC029D50A0>,"[243.716096, nan, nan, nan, nan, nan, nan, nan...","[187.95544576, nan, nan, nan, nan, nan, nan, n...","[193.52600576, nan, nan, nan, nan, nan, nan, n...","[pp4, tangle, tangle, tangle, tangle, tangle, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[nan, nan, nan, nan, nan, nan, nan, nan, nan, ...","[264.39614464, nan, nan, nan, nan, nan, nan, n...",...,"[3.8499999997907253, nan, nan, nan, nan, nan, ...","[-0.9358412702915131, nan, nan, nan, nan, nan,...","[6.260050712827287, nan, nan, nan, nan, nan, n...","[2.809647338769118, nan, nan, nan, nan, nan, n...","[2.5499999999397005, nan, nan, nan, nan, nan, ...","[1.5654388136339699, nan, nan, nan, nan, nan, ...","[-12.682009379794703, nan, nan, nan, nan, nan,...","[1.7235509172971957, nan, nan, nan, nan, nan, ...","[-1.9000000001915396, nan, nan, nan, nan, nan,...","[-1.2679989901645685, nan, nan, nan, nan, nan,..."
9,pp1,pp1-250205-090150,<trial_class.Trial object at 0x000001FC00366F00>,"[241.1626496, nan, 411.16401664, 491.16413952,...","[181.16231168, nan, 190.11239936, 190.52249088...","[181.99232512, nan, 190.48267776, 190.62243328...","[pp4, tangle, pp1, pp4, pp4, pp4, pp1, tangle,...","[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, nan, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, nan, 0.0, 0.0, 0.0, ...","[246.34261504, nan, 415.16401664, 495.16413952...",...,"[1.6899999998418025, nan, 2.4099999998247768, ...","[-0.6266020500182463, nan, 1.1020370860277466,...","[1.2853140698801533, nan, 0.9371456843900628, ...","[1.701397888258207, nan, 1.9939580055971922, 2...","[3.7199999999120337, nan, 2.5899999999387546, ...","[0.3200861046144806, nan, 0.23370519888610852,...","[0.3363055009509661, nan, 10.433666787505604, ...","[1.9469861218608855, nan, 2.7347315168266757, ...","[-6.97000000007165, nan, -3.4600000001546505, ...","[0.03307545987105456, nan, 1.0433096851491601,..."
10,pp5,pp5-250205-095320,<trial_class.Trial object at 0x000001FC02A3C380>,"[240.6948864, 320.6955008, 410.69576192, 490.6...","[180.69438464, 193.3344768, 211.28462336, 218....","[185.18441984, 209.74485504, 214.79473152, 221...","[pp5, pp5, pp5, pp5, pp5, tie, pp5, pp5, pp5, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, nan, 0.0, 0.0, 0.0, ...","[244.6948864, 324.6955008, 414.69576192, 494.6...",...,"[2.8399999998146086, 0.7799999998633211, 1.959...","[0.5815986082760558, 0.324992539492864, 0.6317...","[3.1990444969931384, 1.8901631727444839, -0.52...","[1.4959049892589042, 0.8855829378734035, 0.695...","[1.239999999970678, 2.8099999999335523, 2.0399...","[0.799955300158309, 0.4720584852354011, -0.131...","[-2.4711109406688223, 4.2718221609921425, 6.13...","[0.9189001911124162, 0.7326617320239831, 0.904...","[-1.7500000001950866, -3.0600000001641092, -5....","[-0.2465383444794642, 0.42671692393993405, 0.6..."
11,pp8,pp8-250205-095320,<trial_class.Trial object at 0x000001FC024E3D70>,"[240.6948864, 320.6955008, 410.69576192, 490.6...","[180.69438464, 182.82446848, 184.1545216, 185....","[181.4642688, 183.91482368, 184.84477952, 187....","[pp8, pp7, pp7, pp7, pp7, pp7, pp7, pp8, pp7, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[260.90487808, 324.6955008, 414.69576192, 494....",...,"[1.2899999998512612, 3.7399999997933264, 3.049...","[-0.5947490837140227, -0.0034025181491655144, ...","[6.518672199894331, -1.6371525607254653, -0.87...","[4.291460603549999, 1.1659326400258503, 1.4743...","[3.7199999999120337, 1.3699999999676038, 2.419...","[1.6291448076303476, -0.40909632391335665, -0....","[-5.8207551478891, 4.260894441554983, -5.05444...","[1.3813532488968185, 2.4666985840807394, 2.199...","[-1.9000000001915396, -8.61000000003287, -0.80...","[-0.5818156189173673, 0.42548456215789227, -0...."

### 2. From Sound Cue/Reward Delivery to First Port Entry

In [13]:
def compute_average_peak_hvl_2(
    da_df,
    spont_peaks,
    start_cue='filtered_sound_cues',
    end_cue='first_PE_after_sound_cue',
    offset=5
):
    total_peaks_timestamps = []
    total_peaks_low = 0
    total_peaks_high = 0
    total_low_comp = 0
    total_high_comp = 0
    total_tie = 0

    # For correct stats: store per-cue peak counts (then aggregate per session)
    cue_rows = []  # each entry: {'file', 'condition'(0/1), 'n_peaks'}

    # Loop through each recording/session
    for _, row in da_df.iterrows():
        peak_timestamps = []
        file_name = row['file name']
        trial_peaks = spont_peaks[spont_peaks['file name'] == file_name]

        hvl_labels = row.get('HVL_Comp') or []
        starts = row.get(start_cue) or []
        ends = row.get(end_cue) or []

        # Loop safely over aligned indices
        n = min(len(hvl_labels), len(starts), len(ends))
        for i in range(n):
            # Skip NaN/None cue times
            s = starts[i]
            e = ends[i]
            if s is None or (isinstance(s, float) and np.isnan(s)):
                continue
            if e is None or (isinstance(e, float) and np.isnan(e)):
                continue

            # Only analyze low/high (0/1); count others as ties
            lab_int = hvl_labels[i]
            if lab_int == 0:
                total_low_comp += 1
            elif lab_int == 1:
                total_high_comp += 1
            else:
                total_tie += 1
                continue

            start = float(s)
            end = float(e) + float(offset)

            # Filter to get the peaks in window
            peaks_in_windows = trial_peaks[
                (trial_peaks['event_time'] >= start) &
                (trial_peaks['event_time'] <= end)
            ]
            n_peaks = int(len(peaks_in_windows))

            # Update totals
            if lab_int == 0:
                total_peaks_low += n_peaks
            elif lab_int == 1:
                total_peaks_high += n_peaks

            # Store cue-level count for session-level paired stats
            cue_rows.append({
                'file': file_name,
                'condition': lab_int,   # 0 low, 1 high
                'n_peaks': n_peaks
            })

            # Save peak timestamps for this session (optional)
            if n_peaks > 0:
                peak_timestamps.extend(peaks_in_windows['event_time'].tolist())

        total_peaks_timestamps.append(peak_timestamps)

    # Add column back into da_df
    da_df = da_df.copy()
    da_df['Timestamps of Peak in Comp'] = total_peaks_timestamps

    # Print totals
    print("Low competition:")
    print("  Total peaks:", total_peaks_low)
    print("  Total cues:", total_low_comp)
    print("  Average #:", (total_peaks_low / total_low_comp) if total_low_comp else np.nan)

    print("\nHigh competition:")
    print("  Total peaks:", total_peaks_high)
    print("  Total cues:", total_high_comp)
    print("  Average #:", (total_peaks_high / total_high_comp) if total_high_comp else np.nan)

    print("\nTotal ties:", total_tie)

    # -------------------------------
    # Correct paired session-level stats
    # -------------------------------
    cue_df = pd.DataFrame(cue_rows)
    if cue_df.empty:
        print("\n[Stats] No valid low/high cue windows found. Cannot run stats.")
        return da_df

    # Compute per-session mean peaks per cue for each condition
    session_means = (
        cue_df
        .groupby(['file', 'condition'])['n_peaks']
        .mean()
        .unstack('condition')   # columns: 0 (low), 1 (high) if present
    )

    # Keep only sessions that have BOTH conditions (paired)
    paired = session_means.dropna(subset=[0, 1], how='any')
    print(paired)

    if len(paired) < 2:
        print("\n[Stats] Not enough paired sessions (need >= 2 with both low and high) to run Wilcoxon.")
        return da_df

    low_means = paired[0].to_numpy()
    high_means = paired[1].to_numpy()
    diffs = high_means - low_means

    print("\n[Stats] Session-level mean peaks per cue")
    print("  n paired sessions:", len(paired))
    print("  Mean low:", float(np.mean(low_means)))
    print("  Mean high:", float(np.mean(high_means)))
    print("  Mean diff (high - low):", float(np.mean(diffs)))
    print("  Median diff (high - low):", float(np.median(diffs)))

    # Paired Wilcoxon signed-rank test
    w_stat, p_val = wilcoxon(high_means, low_means, zero_method='wilcox', alternative='two-sided')
    print("\nWilcoxon signed-rank test (paired)")
    print("  W statistic:", float(w_stat))
    print("  p-value:", float(p_val))

    # return da_df

In [14]:
compute_average_peak_hvl_2(mPFC_rc_exp, rc_exp.spont_peaks)
# mPFC_rc_exp

Low competition:
  Total peaks: 588
  Total cues: 513
  Average #: 1.1461988304093567

High competition:
  Total peaks: 48
  Total cues: 52
  Average #: 0.9230769230769231

Total ties: 84
condition               0.0       1.0
file
p1-240611-082555   0.615385  1.000000
p2-240613-104938   1.583333  2.250000
p3-240611-110619   0.800000  0.500000
p5-240913-085922   0.647059  0.000000
p5-240915-064653   2.000000  0.400000
p7-240912-090250   0.625000  0.250000
p7-240914-074210   0.333333  0.000000
p8-240913-070924   0.562500  0.000000
p8-240915-051905   1.625000  0.833333
p8-240915-081607   0.700000  1.000000
pp2-250205-122507  1.461538  0.666667
pp3-250204-122327  1.611111  5.000000
pp3-250206-093423  1.083333  1.000000
pp5-250203-080636  1.250000  0.000000
pp5-250204-104135  0.800000  3.333333
pp5-250205-095320  0.866667  0.666667
pp7-250206-062728  1.307692  0.000000

[Stats] Session-level mean peaks per cue
  n paired sessions: 17
  Mean low: 1.051291293289563
  Mean high: 0.9941176470588234
  Mean diff (high - low): -0.057173646230739686
  Median diff (high - low): -0.3333333333333333

Wilcoxon signed-rank test (paired)
  W statistic: 53.5
  p-value: 0.27618520590056084